export const puroks = [
  "Purok 1 - Mabini",
  "Purok 2 - Rizal",
  "Purok 3 - Bonifacio",
  "Purok 4 - Aguinaldo",
  "Purok 5 - Bagong Buhay",
  "Purok 6 - Maliwanag",
];

export const mockBlotterCases = [
  {
    id: "BLT-0031",
    incidentType: "Noise Complaint",
    location: "Purok 1 - Mabini",
    coordinates: { lat: 15.1950, lng: 119.8705 },
    reportedBy: "Maria Santos",
    reportedById: "res-002",
    respondent: "Jose Reyes",
    status: "investigating" as const,
    date: "2026-04-01",
    time: "14:30",
    description: "Loud music from neighbor's house disturbing peace.",
    narrative: "Respondent was playing loud music past midnight on multiple occasions.",
    witnesses: ["Carlos Mañago"],
    notifyParties: true,
    assignedTo: "Kap. Rolando Borja",
  },
  {
    id: "BLT-0030",
    incidentType: "Property Dispute",
    location: "Purok 2 - Rizal",
    coordinates: { lat: 15.1960, lng: 119.8710 },
    reportedBy: "Juan dela Cruz",
    reportedById: "res-001",
    respondent: "Pedro Villanueva",
    status: "mediation" as const,
    date: "2026-03-28",
    time: "09:15",
    description: "Dispute over boundary of property.",
    narrative: "Complainant alleges respondent constructed fence beyond their legal boundary.",
    witnesses: ["Anna Cruz", "Ben Torres"],
    notifyParties: true,
    assignedTo: "Kap. Rolando Borja",
  },
  {
    id: "BLT-0029",
    incidentType: "Theft",
    location: "Purok 3 - Bonifacio",
    coordinates: { lat: 15.1940, lng: 119.8695 },
    reportedBy: "Ana Torres",
    reportedById: "res-003",
    status: "reported" as const,
    date: "2026-03-25",
    time: "22:45",
    description: "Motorcycle stolen from residence.",
    narrative: "Complainant's motorcycle was taken from their front yard.",
    witnesses: [],
    notifyParties: true,
  },
  {
    id: "BLT-0028",
    incidentType: "Verbal Abuse",
    location: "Purok 4 - Aguinaldo",
    coordinates: { lat: 15.1945, lng: 119.8715 },
    reportedBy: "Rosa Magtoto",
    reportedById: "res-004",
    respondent: "Victor Cabarles",
    status: "resolved" as const,
    date: "2026-03-20",
    time: "11:00",
    description: "Verbal altercation in the marketplace.",
    narrative: "Respondent hurled insults at complainant in public.",
    witnesses: ["Marco Garcia"],
    notifyParties: false,
    assignedTo: "Kap. Rolando Borja",
    resolution: "Parties reconciled through mediation. Both issued written apology.",
  },
  {
    id: "BLT-0027",
    incidentType: "Domestic Issue",
    location: "Purok 5 - Bagong Buhay",
    coordinates: { lat: 15.1935, lng: 119.8700 },
    reportedBy: "Elena Soriano",
    reportedById: "res-005",
    status: "escalated" as const,
    date: "2026-03-15",
    time: "03:30",
    description: "Domestic disturbance reported by neighbor.",
    narrative: "Repeated domestic incidents. Referred to higher authority.",
    witnesses: ["Nena Alcantara"],
    notifyParties: true,
    assignedTo: "PNP San Antonio",
  },
];

export const mockProjects = [
  {
    id: "PRJ-001",
    title: "Feeding Program 2026",
    description: "Monthly feeding program for malnourished children and senior citizens in all puroks.",
    category: "Health & Nutrition",
    status: "ongoing" as const,
    startDate: "2026-01-15",
    endDate: "2026-12-15",
    location: "All Puroks",
    budget: 150000,
    actualCost: 45000,
    leadBy: "Kap. Rolando C. Borja",
    beneficiaries: 120,
    requirements: ["Food supplies", "Volunteer coordinators", "Venue setup"],
    milestones: [
      { name: "Program Launch", date: "2026-01-15", status: "completed" as const },
      { name: "Q1 Distribution", date: "2026-03-31", status: "completed" as const },
      { name: "Q2 Distribution", date: "2026-06-30", status: "pending" as const },
      { name: "Year-End Assessment", date: "2026-12-15", status: "pending" as const },
    ],
    fundSource: "Barangay Development Fund",
  },
  {
    id: "PRJ-002",
    title: "Road Rehabilitation - Purok 3",
    description: "Repair and improvement of damaged roads in Purok 3 Bonifacio to improve accessibility.",
    category: "Infrastructure",
    status: "planning" as const,
    startDate: "2026-05-01",
    endDate: "2026-07-31",
    location: "Purok 3 - Bonifacio",
    budget: 500000,
    actualCost: 0,
    leadBy: "Coun. Jose L. Reyes",
    beneficiaries: 350,
    contractor: "JMRC Construction",
    contractorContact: "0912-234-5678",
    requirements: ["DPWH Clearance", "Environmental Compliance Certificate"],
    milestones: [
      { name: "Planning & Design", date: "2026-04-30", status: "completed" as const },
      { name: "Procurement", date: "2026-05-15", status: "pending" as const },
      { name: "Construction Phase 1", date: "2026-06-30", status: "pending" as const },
      { name: "Completion & Turnover", date: "2026-07-31", status: "pending" as const },
    ],
    fundSource: "20% Development Fund",
  },
  {
    id: "PRJ-003",
    title: "Livelihood Training: Handicrafts",
    description: "Skills training for unemployed residents in handicraft production for income generation.",
    category: "Livelihood",
    status: "completed" as const,
    startDate: "2026-02-01",
    endDate: "2026-03-31",
    location: "Barangay Hall",
    budget: 80000,
    actualCost: 72000,
    leadBy: "Coun. Ana Maria Reyes",
    beneficiaries: 45,
    requirements: ["Training materials", "Resource speakers"],
    milestones: [
      { name: "Registration", date: "2026-02-01", status: "completed" as const },
      { name: "Training Sessions", date: "2026-03-15", status: "completed" as const },
      { name: "Certification", date: "2026-03-31", status: "completed" as const },
    ],
    fundSource: "TESDA Grant",
  },
  {
    id: "PRJ-004",
    title: "Basketball Court Renovation",
    description: "Renovation and improvement of the barangay basketball court with new flooring and lighting.",
    category: "Sports & Recreation",
    status: "ongoing" as const,
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    location: "Covered Court, Santiago",
    budget: 200000,
    actualCost: 120000,
    leadBy: "Coun. Mark Santos",
    beneficiaries: 800,
    contractor: "BrightBuild Corp",
    contractorContact: "0923-456-7890",
    requirements: ["Building permit", "Electrical permit"],
    milestones: [
      { name: "Design & Planning", date: "2026-03-01", status: "completed" as const },
      { name: "Floor Works", date: "2026-03-31", status: "completed" as const },
      { name: "Lighting Installation", date: "2026-04-20", status: "pending" as const },
      { name: "Completion", date: "2026-04-30", status: "pending" as const },
    ],
    fundSource: "Barangay Development Fund",
  },
];

export const mockOfficials = [
  { id: "off-001", name: "Hon. Rolando C. Borja", position: "Barangay Captain", email: "captain@brgy-santiago.gov.ph", phone: "0912-345-6789" },
  { id: "off-002", name: "Sec. Maria D. Santos", position: "Barangay Secretary", email: "secretary@brgy-santiago.gov.ph", phone: "0923-456-7890" },
  { id: "off-003", name: "Hon. Jose L. Reyes", position: "Barangay Councilor", email: "councilor1@brgy-santiago.gov.ph", phone: "0934-567-8901" },
  { id: "off-004", name: "Hon. Ana Maria Reyes", position: "Barangay Councilor", email: "councilor2@brgy-santiago.gov.ph", phone: "0945-678-9012" },
  { id: "off-005", name: "Hon. Mark Santos", position: "Barangay Councilor", email: "councilor3@brgy-santiago.gov.ph", phone: "0956-789-0123" },
  { id: "off-006", name: "Treas. Carlo Aquino", position: "Barangay Treasurer", email: "treasurer@brgy-santiago.gov.ph", phone: "0967-890-1234" },
];

export const mockAssets = [
  {
    id: "AST-001",
    name: "Barangay Multi-Purpose Vehicle",
    category: "Vehicle" as const,
    description: "Toyota Hi-Ace Van for community transport and emergency use",
    acquisitionDate: "2022-06-15",
    acquisitionCost: 1200000,
    condition: "Good" as const,
    location: "Barangay Hall Garage",
    accountableOfficer: "Hon. Rolando C. Borja",
    serialNumber: "TAV-2022-001",
  },
  {
    id: "AST-002",
    name: "Desktop Computer Set",
    category: "IT Equipment" as const,
    description: "Office computer with complete peripherals for records management",
    acquisitionDate: "2023-01-10",
    acquisitionCost: 45000,
    condition: "Excellent" as const,
    location: "Barangay Hall Office",
    accountableOfficer: "Sec. Maria D. Santos",
    serialNumber: "CPU-2023-001",
    warranty: "2025-01-10",
  },
  {
    id: "AST-003",
    name: "Generator Set (10KVA)",
    category: "Equipment" as const,
    description: "Emergency power generator for barangay hall",
    acquisitionDate: "2021-08-20",
    acquisitionCost: 85000,
    condition: "Fair" as const,
    location: "Barangay Hall Basement",
    accountableOfficer: "Hon. Rolando C. Borja",
    serialNumber: "GEN-2021-001",
  },
  {
    id: "AST-004",
    name: "Conference Table Set",
    category: "Furniture" as const,
    description: "12-seater conference table with matching chairs",
    acquisitionDate: "2020-03-15",
    acquisitionCost: 35000,
    condition: "Good" as const,
    location: "Barangay Hall Conference Room",
    accountableOfficer: "Sec. Maria D. Santos",
  },
];

export const mockOrdinances = [
  {
    id: "ORD-001",
    number: "BO-2026-001",
    title: "AN ORDINANCE REGULATING NOISE POLLUTION IN BARANGAY SANTIAGO",
    type: "Ordinance" as const,
    dateEnacted: "2026-01-15",
    author: "Hon. Rolando C. Borja",
    status: "Active" as const,
    summary: "Establishes noise level standards and penalties for violations within the barangay.",
    fullText: `Section 1. Title. This ordinance shall be known as the "Barangay Santiago Noise Control Ordinance of 2026."\n\nSection 2. Declaration of Policy. The barangay recognizes the right of every resident to a peaceful and quiet environment.\n\nSection 3. Prohibited Acts. No person shall cause, make, or allow noise in excess of 60 decibels between 10:00 PM and 6:00 AM.\n\nSection 4. Penalties. First offense: Warning. Second offense: ₱500.00 fine. Third offense: ₱1,000.00 fine and community service.\n\nSection 5. Effectivity. This ordinance shall take effect upon approval.`,
  },
  {
    id: "ORD-002",
    number: "BRes-2026-001",
    title: "RESOLUTION AUTHORIZING THE BARANGAY CAPTAIN TO ENTER INTO A MEMORANDUM OF AGREEMENT",
    type: "Resolution" as const,
    dateEnacted: "2026-01-28",
    author: "Barangay Council",
    status: "Active" as const,
    summary: "Authorizes the Barangay Captain to sign a MOA with TESDA for livelihood programs.",
    fullText: `WHEREAS, the Barangay desires to improve the livelihood opportunities of its constituents;\n\nWHEREAS, TESDA has expressed willingness to conduct training programs;\n\nNOW THEREFORE BE IT RESOLVED, as it is hereby resolved to authorize the Barangay Captain to enter into a Memorandum of Agreement with TESDA.`,
  },
  {
    id: "ORD-003",
    number: "BO-2025-012",
    title: "AN ORDINANCE ESTABLISHING A BARANGAY SCHOLARSHIP PROGRAM",
    type: "Ordinance" as const,
    dateEnacted: "2025-11-10",
    author: "Hon. Ana Maria Reyes",
    status: "Active" as const,
    summary: "Creates a scholarship fund for financially-challenged college students from the barangay.",
    fullText: `Section 1. There is hereby established the Barangay Santiago Scholarship Program.\n\nSection 2. Coverage. Qualified college students who are bona fide residents of Barangay Santiago.\n\nSection 3. Benefits. Monthly stipend of ₱2,000 and book allowance of ₱3,000 per semester.\n\nSection 4. Funding. An annual appropriation of ₱200,000 shall be allocated from the barangay budget.`,
  },
];

export const mockAnnouncements = [
  {
    id: "ann-001",
    title: "Clean-Up Drive - April 13, 2026",
    content: "All residents are invited to join the Clean-Up Drive on April 13, 2026 at 6:00 AM. Assembly at Barangay Hall. These activities help maintain cleanliness, prevent diseases, and promote unity among residents.",
    category: "Event",
    priority: "medium" as const,
    date: "2026-04-09",
    author: "Kap. Rolando C. Borja",
  },
  {
    id: "ann-002",
    title: "Free Medical Mission",
    content: "The barangay in partnership with the Municipality of San Antonio will hold a Free Medical Mission on April 20, 2026. Services include general check-up, dental, and eye examination. All residents are welcome.",
    category: "Event",
    priority: "high" as const,
    date: "2026-04-07",
    author: "Kap. Rolando C. Borja",
  },
  {
    id: "ann-003",
    title: "Water Supply Interruption Notice",
    content: "MAYNILAD will conduct maintenance work on April 15, 2026 from 8:00 AM to 5:00 PM. Water supply will be interrupted in Puroks 1-3. Please store enough water.",
    category: "Maintenance",
    priority: "high" as const,
    date: "2026-04-05",
    author: "Sec. Maria D. Santos",
  },
  {
    id: "ann-004",
    title: "Barangay Assembly - April 28, 2026",
    content: "Mandatory General Assembly for all Barangay Officials and Household Representatives on April 28, 2026 at 9:00 AM at Barangay Plaza. Topics include mid-year budget update and community programs review.",
    category: "Meeting",
    priority: "high" as const,
    date: "2026-04-03",
    author: "Sec. Maria D. Santos",
  },
  {
    id: "ann-005",
    title: "Summer Sports Festival Registration",
    content: "Registration for the Barangay Summer Sports Festival is now open! Events include basketball, volleyball, badminton, and swimming. Register at the Barangay Hall until April 30, 2026.",
    category: "Event",
    priority: "low" as const,
    date: "2026-04-01",
    author: "Coun. Mark Santos",
  },
];

export const mockDocumentRequests = [
  {
    id: "doc-001",
    residentId: "res-001",
    residentName: "Juan dela Cruz",
    documentType: "Barangay Clearance",
    purpose: "Job application",
    status: "approved" as const,
    date: "2026-04-01",
    address: "Purok 1, Barangay Santiago",
    notes: "Ready for release",
  },
  {
    id: "doc-002",
    residentId: "res-002",
    residentName: "Maria Santos",
    documentType: "Certificate of Indigency",
    purpose: "PhilHealth application",
    status: "pending" as const,
    date: "2026-04-05",
    address: "Purok 2, Barangay Santiago",
    notes: "",
  },
  {
    id: "doc-003",
    residentId: "res-003",
    residentName: "Pedro Cruz",
    documentType: "Certificate of Residency",
    purpose: "School enrollment",
    status: "processing" as const,
    date: "2026-04-07",
    address: "Purok 3, Barangay Santiago",
    notes: "Under review",
  },
  {
    id: "doc-004",
    residentId: "res-004",
    residentName: "Ana Torres",
    documentType: "Business Permit",
    purpose: "Sari-sari store renewal",
    status: "rejected" as const,
    date: "2026-03-28",
    address: "Purok 4, Barangay Santiago",
    notes: "Missing requirements: Fire Safety Certificate",
  },
];

export const mockResidents = [
  { id: "RES-001", name: "Juan dela Cruz", email: "juan@email.com", phone: "09123456789", address: "Purok 1, Barangay Santiago", birthDate: "1990-05-15", gender: "Male" as const, civilStatus: "Married" as const, status: "active" as const },
  { id: "RES-002", name: "Maria Santos", email: "maria@email.com", phone: "09987654321", address: "Purok 2, Barangay Santiago", birthDate: "1985-09-22", gender: "Female" as const, civilStatus: "Single" as const, status: "active" as const },
  { id: "RES-003", name: "Pedro Cruz", email: "pedro@email.com", phone: "09876543210", address: "Purok 3, Barangay Santiago", birthDate: "1978-12-01", gender: "Male" as const, civilStatus: "Married" as const, status: "active" as const },
  { id: "RES-004", name: "Ana Torres", email: "ana@email.com", phone: "09765432109", address: "Purok 4, Barangay Santiago", birthDate: "1995-03-18", gender: "Female" as const, civilStatus: "Single" as const, status: "inactive" as const },
  { id: "RES-005", name: "Carlos Reyes", email: "carlos@email.com", phone: "09654321098", address: "Purok 5, Barangay Santiago", birthDate: "1968-07-30", gender: "Male" as const, civilStatus: "Widowed" as const, status: "active" as const },
];

export const mockBusinesses = [
  { id: "biz-001", businessName: "Tindahan ni Nena", ownerName: "Elena Soriano", type: "Retail (Sari-Sari Store)", address: "Purok 1, Santiago", permitNumber: "BP-2026-001", status: "active" as const },
  { id: "biz-002", businessName: "Rosa's Carinderia", ownerName: "Rosa Magtoto", type: "Food & Beverage", address: "Purok 2, Santiago", permitNumber: "BP-2026-002", status: "active" as const },
  { id: "biz-003", businessName: "Santiago Auto Parts", ownerName: "Victor Cabarles", type: "Services", address: "Purok 3, Santiago", permitNumber: "BP-2025-010", status: "expired" as const },
  { id: "biz-004", businessName: "JV Construction Supply", ownerName: "Jose Villanueva", type: "Construction", address: "Purok 4, Santiago", permitNumber: "", status: "pending" as const },
];
