import { pgTable, text, numeric, integer, boolean, date, timestamp, jsonb } from "drizzle-orm/pg-core";

export const announcements = pgTable("announcements", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  title: text("title").notNull(),
  subject: text("subject"),
  category: text("category").default("General"),
  priority: text("priority").default("medium"),
  content: text("content").notNull(),
  eventDate: text("event_date"),
  eventTime: text("event_time"),
  venue: text("venue"),
  targetGroups: text("target_groups").array(),
  reminders: text("reminders"),
  contactInfo: text("contact_info"),
  issuedBy: text("issued_by"),
  author: text("author").notNull(),
  date: text("date"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const ordinances = pgTable("ordinances", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  number: text("number").notNull(),
  title: text("title").notNull(),
  type: text("type").notNull(),
  dateEnacted: text("date_enacted"),
  author: text("author"),
  status: text("status").default("Active"),
  summary: text("summary"),
  fullText: text("full_text"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const documentRequests = pgTable("document_requests", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  residentId: text("resident_id"),
  residentName: text("resident_name").notNull(),
  documentType: text("document_type").notNull(),
  purpose: text("purpose").notNull(),
  status: text("status").default("pending"),
  date: text("date"),
  address: text("address"),
  notes: text("notes").default(""),
  paymentAmount: numeric("payment_amount"),
  paymentMethod: text("payment_method"),
  paymentDate: text("payment_date"),
  paymentRef: text("payment_ref"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const blotterCases = pgTable("blotter_cases", {
  id: text("id").primaryKey(),
  incidentType: text("incident_type").notNull(),
  location: text("location").notNull(),
  reportedBy: text("reported_by").notNull(),
  reportedById: text("reported_by_id"),
  respondent: text("respondent"),
  status: text("status").default("reported"),
  date: text("date"),
  time: text("time"),
  description: text("description"),
  narrative: text("narrative"),
  witnesses: text("witnesses").array(),
  assignedTo: text("assigned_to"),
  resolution: text("resolution"),
  resolutionDetails: text("resolution_details"),
  agreementDetails: text("agreement_details"),
  remarks: text("remarks"),
  cancellationReason: text("cancellation_reason"),
  rejectionReason: text("rejection_reason"),
  notifyParties: boolean("notify_parties").default(true),
  hearing: jsonb("hearing"),
  complainantPresent: boolean("complainant_present"),
  respondentPresent: boolean("respondent_present"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const projects = pgTable("projects", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  title: text("title").notNull(),
  description: text("description"),
  category: text("category"),
  status: text("status").default("planning"),
  startDate: text("start_date"),
  endDate: text("end_date"),
  location: text("location"),
  budget: numeric("budget").default("0"),
  actualCost: numeric("actual_cost").default("0"),
  leadBy: text("lead_by"),
  beneficiaries: integer("beneficiaries").default(0),
  contractor: text("contractor"),
  contractorContact: text("contractor_contact"),
  requirements: text("requirements").array(),
  milestones: jsonb("milestones").default([]),
  fundSource: text("fund_source"),
  workPlan: jsonb("work_plan").default([]),
  budgetItems: jsonb("budget_items").default([]),
  objectives: text("objectives"),
  targetBeneficiaries: text("target_beneficiaries"),
  duration: text("duration"),
  expectedOutput: text("expected_output"),
  monitoring: text("monitoring"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const residents = pgTable("residents", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(),
  email: text("email"),
  phone: text("phone"),
  address: text("address"),
  birthDate: text("birth_date"),
  gender: text("gender"),
  civilStatus: text("civil_status"),
  status: text("status").default("active"),
  purok: text("purok"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const assets = pgTable("assets", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(),
  category: text("category"),
  description: text("description"),
  acquisitionDate: text("acquisition_date"),
  acquisitionCost: numeric("acquisition_cost").default("0"),
  condition: text("condition").default("Good"),
  location: text("location"),
  accountableOfficer: text("accountable_officer"),
  serialNumber: text("serial_number"),
  warranty: text("warranty"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const businesses = pgTable("businesses", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  businessName: text("business_name").notNull(),
  ownerName: text("owner_name").notNull(),
  type: text("type"),
  address: text("address"),
  permitNumber: text("permit_number"),
  status: text("status").default("pending"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  email: text("email").unique().notNull(),
  fullName: text("full_name").notNull(),
  role: text("role").notNull(),
  address: text("address"),
  phone: text("phone"),
  purok: text("purok"),
  createdAt: timestamp("created_at").defaultNow(),
});
